### ISSUE TITLE
Unable to modify requests displayed in the HTTP history tab

### ISSUE THREAD

**Issue by cloud-jie** [PortSwigger/burp-extensions-montoya-api#102]
I am using montoya-api version 2024.7, and burp suite version 2024.8.4.

I have tried to use the handleRequestReceived method, the documentation describes that this method is called before the Proxy receives the HTTP request, according to the documentation I should be able to modify the request packet displayed in the http history, but I failed, the modifications are only visible in the Logger tab.
I have also tried other related api's such as registerHttpHandler, etc., but they still don't work!

**Comment by Hannah-PortSwigger** [comment]
Hi

If you're using a ProxyRequestHandler and making changes in "handleRequestReceived()", you should see these changes reflected in the Proxy History.
You should see that the "Edited" column is checked. If you change the dropdown on the request from "Original request" to "Edited request", you should see your modifications.
