### ISSUE TITLE
[burp.api.montoya.utilities.json] Request method to get JSON parameter location with one click

### ISSUE THREAD

**Issue by cloud-jie** [PortSwigger/burp-extensions-montoya-api#104]
All methods of burp.api.montoya.utilities.json accept JSON strings and positions. However, for such an important position, there is no method that can get the position of all parameters in one click.

![image](https://github.com/user-attachments/assets/c1a84ed0-af1b-45c3-a5e4-2f6e11674ba8)

In addition, will burp.api.montoya.utilities.CryptoUtils provide encryption methods such as aes, rsa, sm2, sm4, des, etc. in the future?

**Comment by Michelle-PortSwigger** [comment]
Hi

If you don't know the structure of the JSON and need to walk it/interrogate it you might find the JsonNode interface useful as a starting point:
https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/utilities/json/JsonNode.html
I hope this helps.

For your second question, we don't have any current plans to provide encryption methods as part of burp.api.montoya.utilities.CryptoUtils, if we did in the future we would just be wrapping existing Java APIs, so in the emantime you may want to check out the JCEs (Java cryptography extensions).

**Comment by Hannah-PortSwigger** [comment]
Hi @cloud-jie 

You can update a JSON value that you don't know the location of in the following way:
```java
JsonUtils utils = utilities().jsonUtils();
String json = "{\"foo\":\"bar\"}";

JsonObjectNode obj = JsonNode.jsonNode(json).asObject();
obj.putString("foo", "baz");

String newJson = obj.toJsonString();
```
Hope this helps!

**Comment by Hannah-PortSwigger** [comment]
Hi @cloud-jie 

The Montoya JsonUtils and JsonNode implementations are only intended as simple helper tools for JSON parsing/manipulation. For more complex use cases, we would recommend using a third-party library.
