### ISSUE TITLE
JTree unusual behavior

### ISSUE THREAD

**Issue by cloud-jie** [PortSwigger/burp-extensions-montoya-api#105]
Only load the plugin and do nothing. JTree behaves as shown below.
![image](https://github.com/user-attachments/assets/7fd7da2e-3a16-4e62-84d3-be70a8e8397e)
After clicking all nodes, as shown below
![image](https://github.com/user-attachments/assets/432d0225-df3c-40ca-bd74-5e4d2b8c28d7)

Their behavior is always strange. Initially, the hierarchy is not displayed, and later, after clicking, the hierarchy is still not fully displayed.
The test code is as follows
[myTab.txt](https://github.com/user-attachments/files/17819210/myTab.txt)

**Comment by Michelle-PortSwigger** [comment]
Hi

So we can look into this in a bit more detail and make sure we match your environment properly when testing, can you send the output from Help > Diagnostics for your installation of Burp to support@portswigger.net, please?

**Comment by Hannah-PortSwigger** [comment]
Hi

The reason that this is occurring is that we have a custom UI delegate changing the layout of this component.

You can override this by explicitly setting your own UI:
```java
tree.setUI(new BasicTreeUI());
```

Alternatively, if you would like to keep your theming more in line with Burp's, you can import FlatLaf as a compileOnly dependency, and use FlatLaf's theming options:
```java
tree.setUI(new FlatTreeUI());
```
