### ISSUE TITLE
importProjectOptionsFromJson redirect to dashboard forcibly ?

### ISSUE THREAD

**Issue by InfiniteOpen** [PortSwigger/burp-extensions-montoya-api#106]
When I use 
`burp.api.montoya.burpsuite.BurpSuite#importProjectOptionsFromJson` in my plugin ,to load my configurations

For example when I click a button in the repeater tab that triggers the `burp.api.montoya.burpsuite.BurpSuite#importProjectOptionsFromJson` function , the tab will redirect  to the dashboard forcibly.
![screen_recording_2024-12-11_17-48-17](https://github.com/user-attachments/assets/c198ada3-c2ff-4ed8-8d37-0833fb32465c)

Could you please help me figure out what happens when triggering the function `burp.api.montoya.burpsuite.BurpSuite#importProjectOptionsFromJson` function  , and how to prevent redirect from this action ?

ps: i tried to share my burp plugin with my friends, and nothing like above happened. they are using win11 operating system, but mine is win10.

**Comment by Hannah-PortSwigger** [comment]
Hi. The default behavior of Burp when loading in new project options or user options is to reset to the Dashboard tab. This also occurs if you manually load new user/project options. We don't have any plans to change this behavior, but we do have a feature request that I have added your +1 to.

The changes in your UI where you are missing part of the screen are not expected, so we would recommend emailing support (support@portswigger.net) to look into this further.
