### ISSUE TITLE
HttpResponseReceived get Chinese characters error

### ISSUE THREAD

**Issue by yunxiaoshu** [PortSwigger/burp-extensions-montoya-api#107]
HttpResponseReceived   responseReceived

responseReceived.bodyToString()
responseReceived.withBody

issue:
When there are Chinese characters in the response content, garbled characters will be output

**Comment by Hannah-PortSwigger** [comment]
Hi

When converting multi-byte data between bytes and String, Burp will truncate data. We'd recommend keeping your data in ByteArray form as much as possible to prevent this.

If you have some specifics that you'd like us to look into in more detail, please drop us an email at support@portswigger.net.
