### ISSUE TITLE
Not able to control the Burp using Web APIs 

### ISSUE THREAD

**Issue by Ayush170-Future** [PortSwigger/burp-extensions-montoya-api#109]
I have a unique requirement where I need to dynamically control Burp Suite from within my Spring Boot service, which has multiple APIs.

Is it possible to use Montoya APIs to achieve this?

Specifically, I'm interested in knowing if I can dynamically set a custom header value in Burp Suite through one of my Spring Boot APIs.

**Comment by Ayush170-Future** [comment]
@SeanBurnsUK would really appreciate it if you could answer this, please!

**Comment by SeanBurnsUK** [comment]
You should be able to accomplish this using the Montoya API. By hooking into the HTTP listener, you can modify headers. To "dynamically" control this behaviour, there are a few options, all of which involve "exposing" your extension to your Spring application. This can be achieved via RPC, sockets, HTTP, etc.

The simplest approach might be for your Burp extension to start a web server (e.g., Vert.x, JDK HttpServer, etc.) and expose an HTTP endpoint. Your Spring application can then connect to this HTTP endpoint and control your extension in whatever way you prefer.

**Comment by Hannah-PortSwigger** [comment]
Hi @Ayush170-Future 

As Sean has mentioned, we'd recommend dropping us an email at support@portswigger.net with some more information about how you're using Burp with your service, and some more specifics about the dynamic header you are trying to set.
