### ISSUE TITLE
differert Montoya-Api

### ISSUE THREAD

**Issue by Giftedboy** [PortSwigger/burp-extensions-montoya-api#13]
It is differert between Montoya-Api downloaded from Github and Montoya-Api exported from BurpSuite application，so which one is supposed to be used when i want to make a extension?

**Comment by yxw21** [comment]
Github currently requires burpsuite version 2022.11 for the latest api. 
You can refer to him https://portswigger.net/burp/documentation/desktop/extensions/creating

**Comment by Hannah-PortSwigger** [comment]
The current GitHub version (release 0.10.1) is level with the Early Adopter version of Burp.

If you're currently on the stable channel, you will need to use the previous release (release 0.9.25): https://github.com/PortSwigger/burp-extensions-montoya-api/tree/45377e6724627be3bef450bac1a0d8421b514ad9
