### ISSUE TITLE
Updating annotations on proxy history items 

### ISSUE THREAD

**Issue by Kavakuo** [PortSwigger/burp-extensions-montoya-api#2]
Hi,

I had a look at the new API and really appreciate the new API design!

While prototyping an extension, I noticed that it does not (yet) seem to be possible to update the annotations (highlight color and comment) of existing items in the proxy history. Would it be possible to add a method to the [ProxyRequestResponse](https://github.com/PortSwigger/burp-extensions-montoya-api/blob/main/src/main/java/burp/api/montoya/proxy/ProxyRequestResponse.java) or [Annotations](https://github.com/PortSwigger/burp-extensions-montoya-api/blob/main/src/main/java/burp/api/montoya/core/Annotations.java) interface that would allow to update the annotation, similar to the methods available on the older [IHttpRequestResponse](https://github.com/PortSwigger/burp-extender-api/blob/master/src/main/java/burp/IHttpRequestResponse.java#L81) interface?

**Comment by SeanBurnsUK** [comment]
Thanks for the feedback.

We will be adding this to the api. We are discussing the best way to update the annotations.

**Comment by SeanBurnsUK** [comment]
Version 1.0.0 of the API now has an option to update the annotations. We will be releasing it next week.

You can see the api on the [Dev Branch](https://github.com/PortSwigger/burp-extensions-montoya-api/tree/dev).
