### ISSUE TITLE
Custom tabs are not showing, what can I do?

### ISSUE THREAD

**Issue by cloud-jie** [PortSwigger/burp-extensions-montoya-api#23]
Version 2023.1, the code is as follows：

### public Registration xregisterSuiteTab() {
            return api.userInterface().registerHttpRequestEditorProvider(editorCreationContext -> new ExtensionProvidedHttpRequestEditor() {
                @Override
                public HttpRequest getRequest() {
                    return null;
                }

                @Override
                public void setRequestResponse(HttpRequestResponse httpRequestResponse) {

                }

                @Override
                public boolean isEnabledFor(HttpRequestResponse httpRequestResponse) {
                    return false;
                }

                @Override
                public String caption() {
                    return "xxxxxxxxxxxxxxxxx";
                }

                @Override
                public Component uiComponent() {
                    JPanel jp = new JPanel();
                    jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
                    jp.add(new JLabel("Test Label"));
                    return jp;
                }

                @Override
                public Selection selectedData() {
                    return null;
                }

                @Override
                public boolean isModified() {
                    return false;
                }
            });
        }

Also, can there be a complete sample reference file?

**Comment by SeanBurnsUK** [comment]
Hi,

Yes, this is a bug in burp suite. See [https://github.com/PortSwigger/burp-extensions-montoya-api/issues/19](https://github.com/PortSwigger/burp-extensions-montoya-api/issues/19).

There is a work around for now. Return the same component from uiComponent() instead of creating a new one every time.

eg. for your example.

```
  JPanel jp = new JPanel();
  jp.setLayout(new BoxLayout(jp, BoxLayout.PAGE_AXIS));
  jp.add(new JLabel("Test Label"));

  return api.userInterface().registerHttpRequestEditorProvider(editorCreationContext -> new ExtensionProvidedHttpRequestEditor() {
            @Override
            public HttpRequest getRequest() {
                return null;
            }

            @Override
            public void setRequestResponse(HttpRequestResponse httpRequestResponse) {

            }

            @Override
            public boolean isEnabledFor(HttpRequestResponse httpRequestResponse) {
                return false;
            }

            @Override
            public String caption() {
                return "xxxxxxxxxxxxxxxxx";
            }

            @Override
            public Component uiComponent() {
                return jp;
            }

            @Override
            public Selection selectedData() {
                return null;
            }

            @Override
            public boolean isModified() {
                return false;
            }
        });
    }
```

**Comment by SeanBurnsUK** [comment]
You need to return "true" for requests you are interested in (or just return true if you want it to always show)

```
@Override
public boolean isEnabledFor(HttpRequestResponse httpRequestResponse) {
    return true;
}
```

**Comment by SeanBurnsUK** [comment]
https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/customrequesteditortab

**Comment by SeanBurnsUK** [comment]
This should be fixed in 2023.2, Closing.

**Comment by Giftedboy** [comment]
Hello,i want to konw how to get the origin MessageEditorHttpRequestResponse Object when i register a custom tab?Looking forward to your reply.
![image](https://github.com/user-attachments/assets/ddd36a4a-a96d-4ff7-b1e1-39a157333518)

**Comment by Hannah-PortSwigger** [comment]
You can use `getRequest()` on the `ExtensionProvidedHttpRequestEditor` to get the contents of the current request.

Hope this helps!
