### ISSUE TITLE
Tab components are not rendered

### ISSUE THREAD

**Issue by Saduff** [PortSwigger/burp-extensions-montoya-api#3]
I compiled the [MultiApiExample.java](https://github.com/PortSwigger/burp-extensions-montoya-api/blob/main/examples/src/main/java/net/portswigger/burp/extender/multi/MultiApiExample.java) and loaded it in Burp. The "My Suite Tab" is added, but the tab is empty, no components are rendered.

```
---------------------------------------------------------------------------------------------------------
BURP PROPERTIES
---------------------------------------------------------------------------------------------------------
Burp Version                     2022.9.3
Build Number                     16600
Update Channel                   Early-Adopter
```

**Comment by Hannah-PortSwigger** [comment]
https://github.com/PortSwigger/burp-extensions-montoya-api/blob/9e52e323f68925335ad4cc662ef2bee3e934278c/examples/src/main/java/net/portswigger/burp/extensions/multiapi/MultiApiExample.java#L77
