### ISSUE TITLE
HttpRequestResponse.request().url() does not return expected value

### ISSUE THREAD

**Issue by petrabrunner** [PortSwigger/burp-extensions-montoya-api#30]
Hi team,  I have the following phenomena: 

When I create a new HttpRequest via the burp-engine via the montoya-api (v 1.0.0) like below - then the uri does not seem to be set to the value I want it to... And I have no idea what I am doing wrong. Could this be a bug in the api? 

```
public static startingPoint(HttpRequestResponse requestResponse) {
        //do something
              
        Logger.debug("ScanThread: request-url before handover: " + requestResponse.request().url());
        requestResponse = prepareRequestBeforeHandoverToScanner(requestResponse); 
        Logger.debug("ScanThread: request-url after handover: " + requestResponse.request().url());

       //do some more things
}

public static HttpRequestResponse prepareRequestBeforeHandoverToScanner(final HttpRequestResponse baseRequestResponse) {
        //do something
        
        //build new HttpRequest
        final String baseUrl = removeProtocolFromURL(baseRequestResponse.request().url());
        final HttpService newService = HttpService.httpService("https://" + updateUrlInRequest(baseUrl, newHostHeaderValue, oldHostHeaderValue));
        final HttpRequest adaptedRequest = HttpRequest.http2Request(newService, adaptedHeaders, baseRequestResponse.request().body());

        Logger.debug("PreScan: adapted request " + adaptedRequest.url());
        return FACTORY.httpRequestResponse(adaptedRequest, baseRequestResponse.response());
}

private static String updateUrlInRequest(String baseUrl, String newHost, String oldHost) {
    Logger.debug("PreScan: old url = " +baseUrl);

    String newUrl = newHost;
    if(baseUrl.equals(oldHost + "/")){
        // if the url was nothing more than '<domainname>/'
        newUrl += "/";
    }else if (baseUrl.contains("/")){
        // else if the url looks like '<domainname>/?abcd/efg'
        //split the string after the first "/" -> {<domainname> ,"?abcd/efg"}
        newUrl += "/" + baseUrl.split("/",2)[1];
    }

    Logger.debug("PreScan: new url = https://" + newUrl);

    return newUrl;
}

public static String removeProtocolFromURL(String url) {
    if (url.startsWith("https://")) {
        url = url.substring(8);
        Logger.trace("PreScan: removed https:// from " + url);
    }
    return url;
}

 ```
 
 and the output from these log-lines are as follows: 
 
 ```
11:47:08.352 DEBUG: ScanThread: request-url before handover: https://<olddomain>/rest/v2/settings/persistence/builtin:problem.notifications/tenant/tenant?includeValues=true&from=1617079279835&to=1617086479835
11:47:08.352 DEBUG: PreScan: old url = <olddomain>/rest/v2/settings/persistence/builtin:problem.notifications/tenant/tenant?includeValues=true&from=1617079279835&to=1617086479835
11:47:08.352 DEBUG: PreScan: new url = https://<newdomain>/rest/v2/settings/persistence/builtin:problem.notifications/tenant/tenant?includeValues=true&from=1617079279835&to=1617086479835
11:47:08.352 DEBUG: PreScan: adapted request https://<newdomain>/
11:47:08.352 DEBUG: ScanThread: request-url after handover: https://<newdomain>/

 ```

this is especially problematic as I want to add the "new HttpRequests" to the scanning engine and if the uri is not correct the whole process does not work...

**Comment by Hannah-PortSwigger** [comment]
Hi.

Could you clarify what the output is that you are expecting?

Have you tried retrieving the host from the `HttpService`, rather than splitting off the protocol and any additional paths from your URL?

**Comment by petrabrunner** [comment]
Hi @Hannah-PortSwigger, sure. 

I would expect the output to be something like: 

```
DEBUG: ScanThread: request-url before handover: https://<olddomain>/<uristring1>
DEBUG: PreScan: old url = <olddomain>/<uristring1>
DEBUG: PreScan: new url = https://<newdomain>/<uristring1>
DEBUG: PreScan: adapted request https://<newdomain>/<uristring1>
DEBUG: ScanThread: request-url after handover: https://<newdomain>/<uristring1>
```

the first 3 logs show what I am expecting. however #4 and 5 do not. The problem is not that the host is incorrect. but that the URI part does not fit. I have the impression that once the HttpRequest did a turn through the burp-engine (via the montoya-api) the uri is truncated after the first '/' following the hostname... 


(hope this also addresses your 2nd question) 

thx

**Comment by SeanBurnsUK** [comment]
It is because you are building a http2 request. Http 2 requests need the correct http2 headers. Does your "adaptedHeaders" have the :path pseudo header see (https://httpwg.org/specs/rfc7540.html#HttpRequest)

I recommend avoiding using http2Request method unless you explicitly looking for HTTP 2 vulnerabilities.

You probably should be using the "header" methods on the base request you have.

eg.

adaptedRequest = baseRequestResponse.request().withAddedHeader("Key", "Value").withUpdatedHeader()... etc

Have you had a look at the examples in the example repo? The traffic redirector looks like it is something you want todo.

https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/trafficredirector.

**Comment by petrabrunner** [comment]
@SeanBurnsUK ah. thx for the hint about the http2request. 😆 I actually thought this method name meant "http TO request" not "http v2 request"... my mistake 😅 

about the examples - yes I did take a look but the code in the trafficredirector didnt catch my eye - I will take a look~ thx!

**Comment by petrabrunner** [comment]
@SeanBurnsUK thx a lot for the hint. can confirm - works now. I would never have found this 😅
