### ISSUE TITLE
API Suggestions : customize test cases in scanner

### ISSUE THREAD

**Issue by Kaide0521** [PortSwigger/burp-extensions-montoya-api#36]
Currently, the test cases cannot be customized in scanner API.  For example, in some scenarios, I only want to test SQL injection cases.
Will the function of selecting test cases be added to scanner in the future?

**Comment by Hannah-PortSwigger** [comment]
Hi

Would you be referring to being able to specify scan configurations for scans launched with the Montoya API?

**Comment by Kaide0521** [comment]
Yes.

**Comment by Kaide0521** [comment]
> Hi
> 
> Would you be referring to being able to specify scan configurations for scans launched with the Montoya API?

Yes.

**Comment by Hannah-PortSwigger** [comment]
At the moment, this is not possible. We have an ongoing feature request for this functionality, to which I have added your +1.

**Comment by Kaide0521** [comment]
> At the moment, this is not possible. We have an ongoing feature request for this functionality, to which I have added your +1.

Can you further consider adding the management function of deleting sitemap to release memory occupation?
