### ISSUE TITLE
Multi Api Error

### ISSUE THREAD

**Issue by Kaide0521** [PortSwigger/burp-extensions-montoya-api#37]
When I implement the new and old interfaces, the IBurpExtenderCallbacks object obtained is null? Why?
like this:
`public class BurpExtender implements BurpExtension, IBurpExtender`

**Comment by Hannah-PortSwigger** [comment]
Hi

Have you had a look at the multi-API example extension, found here: https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/multiapi
