### ISSUE TITLE
Name shadowing

### ISSUE THREAD

**Issue by floyd-fuh** [PortSwigger/burp-extensions-montoya-api#4]
The name "annotations" is being shadowed here:

First "annotations" is imported: 

https://github.com/PortSwigger/burp-extensions-montoya-api/blob/45377e6724627be3bef450bac1a0d8421b514ad9/src/main/java/burp/api/montoya/http/message/MarkedHttpRequestResponse.java#L18

And then redefined here:

https://github.com/PortSwigger/burp-extensions-montoya-api/blob/45377e6724627be3bef450bac1a0d8421b514ad9/src/main/java/burp/api/montoya/http/message/MarkedHttpRequestResponse.java#L46

In general this paints a confusing picture, once annotations() is used in a function call and once annotations is used in a function call...

**Comment by SeanBurnsUK** [comment]
Thanks for the feedback.

We have fixed this issue and you should see the change in a future version.

**Comment by floyd-fuh** [comment]
thx. fyi there is also one in the example extension
