### ISSUE TITLE
Allow URL encoding of all characters

### ISSUE THREAD

**Issue by nollium** [PortSwigger/burp-extensions-montoya-api#41]
Burp allows aggressive URL encoding of all characters:
![image](https://user-images.githubusercontent.com/54525684/226645002-4ed38f97-ca69-4212-a0de-628182c6d026.png)

But the Montoya API doesn't seem to allow access to this conversion:
https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/utilities/URLUtils.html

It could be nice to add a flag to specify the wanted behavior, like the HTML encoding conversions do:
https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/utilities/HtmlUtils.html

**Comment by Hannah-PortSwigger** [comment]
Hi

Thanks for the suggestion! We'll get a feature request raised for this behavior.
