### ISSUE TITLE
Add an ID to requestResponse.

### ISSUE THREAD

**Issue by nollium** [PortSwigger/burp-extensions-montoya-api#42]
[HttpRequestToBeSent](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/http/handler/HttpRequestToBeSent.html) and [HttpResponseReceived](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/http/handler/HttpResponseReceived.html) now have an ID to be able to link an intercepted request and response, the same functionality could be useful for request/response editors as it would allow to identify corresponding request and response editors (that are handling the same requestResponse)

It would be useful in cases where a response editor needs to get some state stored in the editor that was used to edit the originating request

**Comment by Hannah-PortSwigger** [comment]
Hi.

We have an open feature request to be able to attach custom metadata to requests/responses. It sounds like this may be of more value for your use case.

I can add your +1 to this feature request if you would like.
