### ISSUE TITLE
Extension provided Inspector conversions

### ISSUE THREAD

**Issue by nollium** [PortSwigger/burp-extensions-montoya-api#43]
It would be neat to allow extensions to define their own conversions in the Burp inspector:
![image](https://user-images.githubusercontent.com/54525684/226942242-c59def36-b89e-4997-a083-a521432ccbb6.png)

**Comment by Hannah-PortSwigger** [comment]
Hi

Thanks for the feedback! We've raised a feature request for this behavior (linked to #46)
