### ISSUE TITLE
Method withUpdatedParameters() doesn't work as expected

### ISSUE THREAD

**Issue by ByQwert** [PortSwigger/burp-extensions-montoya-api#44]
Hello,

Seems like [withUpdatedParameters()](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/http/message/requests/HttpRequest.html#withUpdatedParameters(burp.api.montoya.http.message.params.HttpParameter...)) method doesn't work as described in the documentation. 
![image](https://user-images.githubusercontent.com/3399375/228101144-8bfe8470-6b45-4bf6-9de7-4d43f6f8a870.png)
Namely it doesn't add a new parameter If a parameter doesn't exist in the request.

The following code used during the test:

```
class MyExtensionProvidedHttpRequestEditor implements ExtensionProvidedHttpRequestEditor {
    [...]
    @Override
    public void setRequestResponse(HttpRequestResponse requestResponse) {
        HttpRequest customTabRequest;

        this.requestResponse = requestResponse;        

        // Updates existent parameter
        customTabRequest = requestResponse.request().withUpdatedParameters(HttpParameter.parameter("getParam", "getValue", HttpParameterType.valueOf("URL")));

        // Doesn't add non-existent parameter
        // customTabRequest = requestResponse.request().withUpdatedParameters(HttpParameter.parameter("getParam2", "getValue2", HttpParameterType.valueOf("URL")));
        
        this.requestEditor.setRequest(customTabRequest);
    }

    @Override
    public HttpRequest getRequest() {
        HttpRequest request;

        // Updates existent parameter
        request = requestEditor.getRequest().withUpdatedParameters(HttpParameter.parameter("getParam", "getValue", HttpParameterType.valueOf("URL")));

        // Doesn't add non-existent parameter
        // request = requestEditor.getRequest().withUpdatedParameters(HttpParameter.parameter("getParam2", "getValue2", HttpParameterType.valueOf("URL")));
        
        return request;
    }
    [...]
}
```

**Comment by SeanBurnsUK** [comment]
We will update the javadoc, it is incorrect.

We will be adding 2 new methods to request to accommodate this requirement.

withHeader() and withParameter()

these methods will do the add or update logic (and are inline with the other methods that do the same.. withMethod, withService etc)
