### ISSUE TITLE
httpVersion() missing from HttpMessage

### ISSUE THREAD

**Issue by nollium** [PortSwigger/burp-extensions-montoya-api#45]
[httpVersion](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/http/message/responses/HttpResponse.html#httpVersion())() is a method common to all [HttpMessages](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/http/message/HttpMessage.html) but is only defined in the concrete classes.

There is no good reason to not have it defined in HttpMessage, other HTTP APIs with a similar OOP architecture like [mitmproxy](https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Message:~:text=message%20body%20already.-,http_version%3A%20str,-HTTP%20version%20string) have no trouble doing it.

**Comment by SeanBurnsUK** [comment]
Thank you. I have added httpVersion to HttpMessage. It will be in the next version of the api.
