### ISSUE TITLE
Extending Decoder Abilities

### ISSUE THREAD

**Issue by ccerne-bf** [PortSwigger/burp-extensions-montoya-api#46]
Hi folks!

I think a neat future feature of the Montoya API could be to extend the capabilities of the Burp Decoder (e.g. add new encoders / decoders).

This would be useful if you had a requirement to decode data in a specific format, for instance, Protobufs. The decoder API would simply allow developers to register a new decoder class that implements some Montoya interface, and that class would implement encode and decode methods.

**Comment by Hannah-PortSwigger** [comment]
Hi

Thanks for the feedback! We've raised a feature request for this functionality.

**Comment by cernec1999** [comment]
Thank you! @Hannah-PortSwigger
