### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by cloud-jie** [PortSwigger/burp-extensions-montoya-api#47]
Reproduction steps:
1. Click on any Repeater tab to switch to the custom HTTP request editor
2. Click on another Repeater tab to switch to the custom HTTP request editor
3. Click on the tab in the first step again
This will cause the tab request in step 1 to be overwritten by the tab request in step 2, possibly due to:
![image](https://user-images.githubusercontent.com/63632785/232253138-2599a6f7-d096-4eb1-9999-533188b3d62e.png)
And, during this process, the setRequestResponse method of the custom HTTP request editor was not requested, was it intentionally designed? May I ask for the reason?

Is it because I wrote the wrong code?

**Comment by Hannah-PortSwigger** [comment]
Hi

Can you provide some more information on what you are trying to do, and the code that you have written?

Have you checked out our example extension that adds an additional tab to the request editor? You can find it here: https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/customrequesteditortab

**Comment by Hannah-PortSwigger** [comment]
HI

Could you please drop us an email at support@portswigger.net so we can look into this in more detail?

**Comment by Hannah-PortSwigger** [comment]
For further context, initialization of the text area needed to be moved into a constructor for the ExtensionProvidedHttpRequestEditor, to avoid a shared text area across multiple places.
