### ISSUE TITLE
Group ID Typo in the Docs

### ISSUE THREAD

**Issue by TheTwitchy** [PortSwigger/burp-extensions-montoya-api#5]
Hi all,

It looks like there may be a typo in the group ID of the README examples. In both the Maven and Gradle versions it says to import the following group and artifact:

```
net.portswigger.burp.extensions:montoya-api
```

However, this doesn't appear to be correct, as that path in the Maven Central repo appears to be unrelated: https://repo.maven.apache.org/maven2/net/portswigger/burp/extensions/

The correct group after some poking around appears to be `net.portswigger.burp.extender`, which resolves correctly to https://repo.maven.apache.org/maven2/net/portswigger/burp/extender/montoya-api/ (note the "extensions" vs "extender", it's subtle). 

If this is correct, I (or whoever), can issue a PR to fix it so that other devs don't run into the same problem in the future.

**Comment by SeanBurnsUK** [comment]
Thanks for the feedback, we have corrected this. 
The artifact will be available at https://repo.maven.apache.org/maven2/net/portswigger/burp/extensions/montoya-api soon.
