### ISSUE TITLE
Add support for determining whether common cookie attributes are set

### ISSUE THREAD

**Issue by nchigmaroff** [PortSwigger/burp-extensions-montoya-api#50]
Hi all,

Thanks for the great work developing Montoya.

As far as I know right now, Montoya's Cookie interface allows the domain, path, expiration, name, and value of a HTTP cookie to be accessed easily. However, there is no support for checking common cookie attributes like _HttpOnly_, _secure_, etc. 

It would be great to have a few additional methods along the lines of httpCookie.isSecure() or httpCookie.isHttpOnly() that return Booleans to make it easy to check security properties of set cookies within extensions. 

Thank you!

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback! We've raised a feature request for this functionality.
We'll continue to monitor the popularity of this request.
