### ISSUE TITLE
Questions about scanner

### ISSUE THREAD

**Issue by Kaide0521** [PortSwigger/burp-extensions-montoya-api#53]
When a URL is first scanned, AuditIssueHandler will receive a notification, but when the URL is scanned again, no notification is received? It means that if I want to retest a URL, it is unknown whether the test result has passed or not.

**Comment by Kaide0521** [comment]
Sorry, l reopen this issue， does Montoya Api support clearing issues from the site map？

**Comment by Hannah-PortSwigger** [comment]
It does not currently support this. This would have to be done manually.

We have a feature request for this functionality, to which I have added your +1.
