### ISSUE TITLE
Errors in Java doc

### ISSUE THREAD

**Issue by floyd-fuh** [PortSwigger/burp-extensions-montoya-api#59]
This return type documentation is wrong:

https://github.com/PortSwigger/burp-extensions-montoya-api/blob/8b6d0c237c29e4821fd7e6595719e1761a75e272/src/main/java/burp/api/montoya/collaborator/InteractionFilter.java#L40

As this function does not return a boolean, but an InteractionFilter. The same issue is present further down:

https://github.com/PortSwigger/burp-extensions-montoya-api/blob/8b6d0c237c29e4821fd7e6595719e1761a75e272/src/main/java/burp/api/montoya/collaborator/InteractionFilter.java#L54

I guess it's a copy-paste error or from an old version of the API (where a boolean was returned and not an InteractionFilter). 

Should read instead: ```@return the `InteractionFilter` for the given id``` (in both cases)

**Comment by Hannah-PortSwigger** [comment]
Thanks for letting us know! We'll get this fixed up :)
