### ISSUE TITLE
The method extension() is undefined for the type MontoyaApi

### ISSUE THREAD

**Issue by checkm50** [PortSwigger/burp-extensions-montoya-api#6]
Hello,
When trying these examples I get an error The method extension() is undefined for the type MontoyaApi.
I had to replace all occurrence of api.extension() to api.misc().<methodname>
Could you please update the code or point me if I am making any mistakes on my side?
FYI, I am using Maven dependency as exmplained at https://github.com/PortSwigger/burp-extensions-montoya-api 
Thanks.

**Comment by SeanBurnsUK** [comment]
Thanks for the feedback.

We are actively updating and modifying this API as we get feedback from our users.

Burp suite 2022.9.5 supports supports version [0.9.25](https://github.com/PortSwigger/burp-extensions-montoya-api/tree/0.9.25) of the api. You can look at those examples and checkout that tag/version.

The next version of Burp Suite (2022.11?) supports the current main branch [main](https://github.com/PortSwigger/burp-extensions-montoya-api) also tagged as 0.10.1

We will be making "breaking" changes to the api based on feedback (such as the misc -> extension rename) until we release version 1.0.

**Comment by Hannah-PortSwigger** [comment]
This distinction has been clarified in our documentation: https://portswigger.net/burp/documentation/desktop/extensions/creating
