### ISSUE TITLE
Declare Burp Pro-Only features as Optional

### ISSUE THREAD

**Issue by floyd-fuh** [PortSwigger/burp-extensions-montoya-api#60]
When I use the following code:

```
val collab: Collaborator = api.collaborator()
val client = collab.createClient()
logging.raiseInfoEvent(client.secretKey.toString())
```

on community edition I get: `java.lang.NullPointerException: Cannot invoke "burp.api.montoya.collaborator.CollaboratorClient.getSecretKey()" because "client" is null`

I guess the best would be if `api.collaborator()` would declare to return `Optional<Collaborator>` rather than `Collaborator`:

https://github.com/PortSwigger/burp-extensions-montoya-api/blob/8b6d0c237c29e4821fd7e6595719e1761a75e272/src/main/java/burp/api/montoya/MontoyaApi.java#L51

And obviously for all other Pro-Only functions it should return an `Optional<>`, right?

**Comment by Hannah-PortSwigger** [comment]
Hi Floyd

Thank you for raising this. We're looking into this and will be considering some solutions to handle this in a better way.

If there's anything else we can help with, then please let us know.

**Comment by floyd-fuh** [comment]
Please also fix the same issue with the `PersistedObject` functions, it says in the Javadoc that it might return null, but doesn't declare it as `Optional`, why? For example:

https://github.com/PortSwigger/burp-extensions-montoya-api/blob/8b6d0c237c29e4821fd7e6595719e1761a75e272/src/main/java/burp/api/montoya/persistence/PersistedObject.java#LL70C5-L70C11

Not knowing when things could be null makes developing a trial and error process. I much rather have the IDE remind me that things could be null and I factor that in from the beginning.
