### ISSUE TITLE
NullPointerException on audit.addRequest()

### ISSUE THREAD

**Issue by 423locked** [PortSwigger/burp-extensions-montoya-api#61]
Hello! I've been trying to run a scan in my extension. Added a httprequest from a string, but got
`java.lang.NullPointerException: Cannot invoke "burp.Zy4b.ZmZ()" because "<parameter5>.Zk" is null
	at burp.Zrqt.Zs(Unknown Source)
	at burp.Zha4.addRequest(Unknown Source)
	at burp.Zha4.addRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zxj9.invoke(Unknown Source)
`

The code was:
`
 @Override
    public void initialize(MontoyaApi api)
    {
        Audit audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));
        audit.addRequest(HttpRequest.httpRequest(new String("http://testphp.vulnweb.com/")));
   }
`

I've also tried with HttpRequest.httpRequestFromUrl("https://testphp.vulnweb.com") but got the same nullpointer exception. Could you please point out the problem?

**Comment by Hannah-PortSwigger** [comment]
Hi

I've tested using `HttpRequest.httpRequestFromUrl()`, and that should work for you.

When providing a String argument to `HttpRequest.httpRequest()`, you will need to provide the request itself, rather than the URL of the site.
For example:
```java
"GET / HTTP/1.1\r\nHost: testphp.vulnweb.com\r\n\r\n"
```
In addition, you will also need to provide it with a valid HttpService.


You should find that the following code works for your purposes:
```java
Audit audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));
audit.addRequest(HttpRequest.httpRequestFromUrl("http://testphp.vulnweb.com/"));
```

**Comment by 423locked** [comment]
Thanks! httpRequestFromUrl work well. Could you please look through another submitted issue by me? I still get an empty statusMessage
