### ISSUE TITLE
audit.statusMessage() seems to be always empty

### ISSUE THREAD

**Issue by 423locked** [PortSwigger/burp-extensions-montoya-api#62]
I've attempted starting an audit and catching statusMessage "finished" in a while loop, but it never happened. Then I've attempted outputting status message every five seconds in case I'd see a "finished" message in a burp audit gui and then the extension would output the same "finished" message, but it also never happened. The output was always empty.

This is the code:
        // initiating an audit
        Audit audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));
        audit.addRequest(HttpRequest.httpRequestFromUrl("http://testaspnet.vulnweb.com//"));

        // actually starting audit
        audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));
        logger.logToOutput("" + audit.statusMessage());
        for (int i = 0; i < 100; i++)
        {
            logger.logToOutput("stat:" + audit.statusMessage());
            try
            {
                Thread.sleep(5000);
            }
            catch (Exception e)
            {

            }
        }

**Comment by Hannah-PortSwigger** [comment]
Hi

Are you adding any items to your audit task using `Audit.addRequest()`?

When no items have been added to the Audit task, an empty message is returned.

**Comment by 423locked** [comment]
Hi, I've added a request with Audit.addRequest(). The code was
        // initiating an audit
        Audit audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));
        audit.addRequest(HttpRequest.httpRequestFromUrl("https://xss.challenge.training.hacq.me/challenges/baby02.php/"));

        // actually starting audit
        audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));

..attempting to ouput a statusmessage..

**Comment by Hannah-PortSwigger** [comment]
Hi

The type of task that an audit starts is a "Live audit". This means that you can add requests to the ongoing task at any point.

If you exclude your "actually starting audit" section, do you receive the expected results? I suspect what is occurring is that by starting a new task, you are then unable to retrieve the results from the original task.

For example:
```java
Audit audit = api.scanner().startAudit(AuditConfiguration.auditConfiguration(BuiltInAuditConfiguration.LEGACY_ACTIVE_AUDIT_CHECKS));
audit.addRequest(HttpRequest.httpRequestFromUrl("https://portswigger-labs.net"));

// Monitor audit status...
```
