### ISSUE TITLE
HttpHandler.handleRequestToBeSent while Auditing and Crawling

### ISSUE THREAD

**Issue by 423locked** [PortSwigger/burp-extensions-montoya-api#63]
Hi! I'm attempting to intercept http requests from audit and crawl tools via HttpHandler.handleRequestToBeSent, but the handlers do not seem to be called.
```
MyHttpHandler

    @Override
    public RequestToBeSentAction handleHttpRequestToBeSent(HttpRequestToBeSent requestToBeSent)
    {
        _logger.logToOutput("im here");
        requestToBeSent.headers().add(HttpHeader.httpHeader("Header", "Value"));
        return RequestToBeSentAction.continueWith(requestToBeSent);
    }

    @Override
    public ResponseReceivedAction handleHttpResponseReceived(HttpResponseReceived responseReceived)
    {
        _logger.logToOutput("im in responserecevied");
        return ResponseReceivedAction.continueWith(responseReceived);
    }
```
And then register http handler in burpExtender with
`api.http().registerHttpHandler(new MollyHttpHandler(api));`

None of the logs inside handlers worked, sadly. Only the log telling that the handler was actually set has worked. Could you please point out what possible the problem is?

**Comment by Hannah-PortSwigger** [comment]
Hi

To clarify, you receive the output "i'm here" from your extension?

If looks like you're trying to add an additional header to your outgoing HTTP request.

You would need to do this in the following way:
```java
@Override
public RequestToBeSentAction handleHttpRequestToBeSent(HttpRequestToBeSent requestToBeSent)
{
    HttpRequest newRequest = requestToBeSent.withAddedHeader("Name", "Value");

    return RequestToBeSentAction.continueWith(newRequest);
}
```

**Comment by 423locked** [comment]
Hey, thanks for the correction of withAddedHeader but the problem is that the extension actually does not output "im here" log message and thus the whole requestToBeSent handler does not run

**Comment by Hannah-PortSwigger** [comment]
Just to verify, you find that the "I'm here" message does not get called, even when traffic is passing through Burp (for example, sending a request in Repeater). The methods in the HttpHandler won't trigger unless there is traffic for them to act upon.

Are you able to provide a link to your code, or share some further examples, please?

Have you checked out any of our example extensions? You can find these here: https://github.com/PortSwigger/burp-extensions-montoya-api-examples

The example extensions are a good starting point on which to build more complex extensions.
Some useful ones for you would probably be the following:
- https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/httphandler
- https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/eventlisteners
- https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/customlogger

**Comment by Hannah-PortSwigger** [comment]
Could you drop us a link to your repo, so we can take a look at it? Alternatively, if you'd prefer to share your code via email, you can get in contact with us at support@portswigger.net.

**Comment by 423locked** [comment]
The problem happens to be in the while loop waiting for the audit to end. When I remove the loop, all the handlers work appropriately. But how could I else wait for the audit to finish and only then generateReport? I can either make handlers work and generate report without waiting (it would be empty) or wait for the audit to finish but the handlers won't work.
