### ISSUE TITLE
How to start REST API from CLI?

### ISSUE THREAD

**Issue by 423locked** [PortSwigger/burp-extensions-montoya-api#68]
I want to use the current REST API with Montoya API extension
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/76900248/8c4e7c45-f420-49c0-ae39-2029ff05b1a4)
with the functionality of adding custom scan configs and editing resource pool.
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/76900248/e631bc62-9311-4ddf-b800-c89f941c5b01)
For automation, I want to start burp with montoya extension via cli and therefore comes up the question - how do I start rest api too?

Or else, where can I find burp rest api jar?

**Comment by Hannah-PortSwigger** [comment]
The REST API is a user-level setting. This means that once you've configured it, the setting will stay the same across different Burp projects.

You can check this by configuring the REST API, closing Burp and relaunching it in the manner that you want, and attempting to access the REST API service URL.

**Comment by 423locked** [comment]
Thanks, I get it that it is user settings. The question is - can I ask burp to run headlessly with this user setting of setting up the rest API? I don't want to open gui to set the user setting of rest API due to the automation reasons.
-------- Original message --------From: Hannah-PortSwigger ***@***.***> Date: 6/15/23  5:03 PM  (GMT+03:00) To: PortSwigger/burp-extensions-montoya-api ***@***.***> Cc: Yaroslav Prishedko ***@***.***>, Author ***@***.***> Subject: Re: [PortSwigger/burp-extensions-montoya-api] How to start REST API from CLI? (Issue #68) 
The REST API is a user-level setting. This means that once you've configured it, the setting will stay the same across different Burp projects.
You can check this by configuring the REST API, closing Burp and relaunching it in the manner that you want, and attempting to access the REST API service URL.

**Comment by Hannah-PortSwigger** [comment]
Hi

I've responded to your email regarding this.
