### ISSUE TITLE
Montoya API - Custom Scanner Check

### ISSUE THREAD

**Issue by kernelpanic-bf** [PortSwigger/burp-extensions-montoya-api#7]
Hi!

Thanks for creating a new Burp Extension API, I am testing the new Montoya API to create a plugin with a custom scanner check.
For this I used the ScanCheck interface and within the activeAudit function I would have the following code:

```
// Enter payload in insertion Point
byte[] req = auditInsertionPoint.buildHttpMessageWithPayload(payload.getBytes());
            
// Launch the request
HttpRequestResponse scanRequestResponse = montoyaApi.http().issueRequest(HttpRequest.httpRequest(req));
```

Does not seem to work yet as most likely doing something wrong here in these lines of code. Any guidance would be appreciated!

Thank you!

**Comment by SeanBurnsUK** [comment]
Our support team has your forum post and will be in touch soon.
