### ISSUE TITLE
Support for HttpRequest copy functions with List<HttpHeader>

### ISSUE THREAD

**Issue by josephwhenry** [PortSwigger/burp-extensions-montoya-api#70]
As per the [docs](https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/http/message/requests/HttpRequest.html), there is support to update a `HttpRequest` with a list of parameters:
- `HttpRequest.withAddedParameters()`
- `HttpRequest.withRemovedParameters()`
- `HttpRequest.withUpdatedParameters()`

Will there be future support for similar methods for Headers? It would be great to be able to pass a List of headers to an Add/Remove/Update function.

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback! WE've raised a feature request to add this functionality.
