### ISSUE TITLE
RawEditor text not wrapping

### ISSUE THREAD

**Issue by nollium** [PortSwigger/burp-extensions-montoya-api#76]
Hello,

I am developing an extension where I need to wrap raw editors in a JTabbedPane.

When displaying a RawEditor not wrapped in anything, the text wraps correctly.
But when I wrap it in a JTabbedPane, it doesn't wrap anymore and displays a scrollbar:
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/54525684/fc557d51-b627-4818-b661-ea1bf47d19cc)

Code used to add the RawEditor:
```Java
private void addEditorToDisplayedTabs(RawEditor editor) {
	final String displayedName = "1";

	final var component = editor.uiComponent();

	this.tabbedPane.addTab(displayedName, component);
}
```
I don't think it is an issue related to how I handle the layout on my side, because I've tried to display a JTextArea instead with the .setLineWrap() option to true and it wraps correctly:
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/54525684/47a43165-7245-4804-b876-159eff3f90ec)
 
Code used to add the JTextArea:
```Java
private void addEditorToDisplayedTabs() {
	final String displayedName = "0"

	final var component = new JTextArea("A-".repeat(100));

	component.setLineWrap(true);
	this.tabbedPane.addTab(displayedName, component);
}
```

Right now the only solution I have is to reimplement RawEditor using a JTextArea, which is not ideal because I loose the RawEditor search bar utilities and have to handle encoding bytes myself while RawEditor directly takes ByteArray-s

It would really help my project if you could provide a way to handle this issue :D

Best regards.

**Comment by Hannah-PortSwigger** [comment]
Hi.

Thanks for reporting this! We'll look into replicating this behavior early next week.

**Comment by Hannah-PortSwigger** [comment]
Hi

Could you provide some more information on the scenario when text wrapping is applied?

When testing out an example extension, and the [Montoya example extension](https://github.com/PortSwigger/burp-extensions-montoya-api-examples/tree/main/customrequesteditortab), there is no text wrapping applied to the contents of the raw editor.

**Comment by nollium** [comment]
Apologies for the confusion earlier.
Upon testing with a sample extension, I realize I made a mistake.
Unlike the native Burp 'raw' request editor, the extensions' raw editors don't offer line wrapping as I had previously thought. 

Here's an image for reference: ![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/54525684/32cd2e46-0ee2-4427-a7be-2a1fd58189d9)



This leads me to a question - is it possible to implement line wrapping within RawEditor? 
The inability to control this aspect seems rather restrictive.

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback!

It's not currently possible to implement line wrapping within the RawEditor. However, I've raised a feature request for this functionality.

If there's anything else we can help with, then please let us know.
