### ISSUE TITLE
ByteArray shadows Kotlin built-in

### ISSUE THREAD

**Issue by floyd-fuh** [PortSwigger/burp-extensions-montoya-api#79]
The montoya API uses ByteArray as one of its class names:

https://portswigger.github.io/burp-extensions-montoya-api/javadoc/burp/api/montoya/core/ByteArray.html

That's very unfortunate, because `byte[]` in Java is already called `ByteArray` in Kotlin:

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte-array/

Whenever you import your ByteArray, you shadow Kotlin's ByteArray.

Even worse, this leads to major confusions in IDEs. IDEs nowadays hide their imports by default (which is usually fine). But in Kotlin we then need to check if Burp's ByteArray was imported, which then shadows Kotlin's ByteArray, etc. IDEs can also automatically convert Java code to Kotlin, but with shadowing the effects are... unpredictable.

Please rename ByteArray if you can.

**Comment by Hannah-PortSwigger** [comment]
Hi.

Unfortunately, this will cause significant breaking changes to existing extensions, so we will not be able to rename this class. I'm sorry that this does not help your use case.
