### ISSUE TITLE
setSearchExpression.setSearchExpression can add two and more keyword?

### ISSUE THREAD

**Issue by ody5sey** [PortSwigger/burp-extensions-montoya-api#82]
I want to search many message to mark

**Comment by Hannah-PortSwigger** [comment]
You could set the search expression to a regular expression. Then the user would just need to enable regex matching on their HTTP message search settings to view all highlighted items.

**Comment by ody5sey** [comment]
Can be directly added regex in editor?

**Comment by Hannah-PortSwigger** [comment]
You can set the expression string to a regular expression, then once the user enables regex matching for the message search settings, it will match with the appropriate contents in the message editor.

**Comment by joanlopez** [comment]
Would be possible to expose the Editor settings through the API? So, we can enable the regular expression by default (programmatically) and replicate the support for markers?

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback! I've added your +1 to our ongoing feature request for this functionality.

We're currently monitoring the popularity of this feature, so we're not able to provide an ETA for when we will be able to implement this functionality.
