### ISSUE TITLE
Problems with updating and building http requests

### ISSUE THREAD

**Issue by irsdl** [PortSwigger/burp-extensions-montoya-api#83]
* Here is what I want to achieve: 
I need to modify proxy requests automatically to replace a certain pattern anywhere within the request (path, querystring, header names, hear values, and body). 

* Here is how I thought I should do it theoretically based on the legacy API:
  * Converting the request from byte to string (hopefully there is no encoding issue and all is utf-8)
  * Replacing the require pattern
  * Update the content-length if it has a body
  * Update the current request with the new request

* Problems I am facing which might be as a result of my lack of Montoya knowledge (I have read the documents and examples):

**I would be thankful if you could provide me with better and more efficient solutions for these if one is available**:
1. There is no raw `replace` function for the `interceptedRequest` object using a RegEx pattern or string. The `interceptedRequest.contains` method only checks the body of a request and ignores everything else so we still need to convert the request to string using something like `montoyaApi.utilities().byteUtils().convertToString(interceptedRequest.toByteArray().getBytes())` which is not really efficient. Can the `interceptedRequest` object support searching the whole request in the future? It will also be beneficial to output a matcher object (rather than a boolean) so we can access the capture groups when a Regular Expression has been used.
  
2. There is no method to update the `content-length` automatically when building a request in Montoya API. The only solution I found was to do this manually after I built the HttpRequest object: `httpRequest.withUpdatedHeader("content-length", String.valueOf(httpRequest.body().length()))`. Do you have a better solution to do this? And can we have a method added to the `interceptedRequest` object so it can update/fix the content-length automatically.

3. I cannot find a way in Montoya API to fix the length when it is a **chunked request** where content-length is not important. The solution might be to use the `parameters` method rather than working with the raw HTTP request, but this solution will certainly limit what we can do as we still need to handle the headers separately (to replace a parameter anywhere) and cannot change the `filename` using the `parameters` method in a request. Is it possible to have even a dirty solution to at least have an attempt to fix the hexadecimal length in a chunked request when they are not correct?

4. When building the HttpRequest object from a string or bytes, the defined methods for HTTP/2 and HTTP are totally different as they accept different parameters. Is it possible to have a generic `HttpRequest.httpRequest` method that can support both versions automatically based on a provided raw request in string or byte? At the moment, I have implemented it like this to not switch between protocols to prevent killing the connection but it not efficient at all:
```
if(interceptedRequest.httpVersion().equalsIgnoreCase("HTTP/2")){
                        String[] headerBody = HTTPMessageHelper.getHeaderAndBody(requestString);
                        String[] justHeaders = headerBody[0].split("\r?\n");

                        List<HttpHeader> headersList = Arrays.stream(justHeaders)
                                .skip(1)
                                .map(HttpHeader::httpHeader)
                                .collect(Collectors.toList());

                        httpRequest = HttpRequest.http2Request(httpService, headersList, headerBody[1]).withMethod(interceptedRequest.method()).withPath(interceptedRequest.path().replaceAll(highlightMatcherToBeRemoved.group(0),""));
                    }else{
                        httpRequest = HttpRequest.httpRequest(httpService, requestString);
                    }
```
I could not find a way to pass the correct path and query string parameters when using `HttpRequest.http2Request` directly. I had to remove the first line of request containing the HTTP method and its version when passing the headers to `HttpRequest.http2Request`. Then as it can be seen above, I had to use the `withMethod` to update the path and method separately. This was not needed when using `HttpRequest.httpRequest` but it would kill the connection if a request was using HTTP/2. The `http2Request` method accept headers and body separately without path and method which has made its usage really difficult. 

5. I also could not find any easy way to convert a HTTP/2 httpRequest object to a HTTP httpRequest object. It would be great if the version could be changed using a provided method for an object based on the HttpRequest class.

**Comment by Hannah-PortSwigger** [comment]
Thanks for the feedback. We're looking into these points in some more detail and we'll get back to you soon.

**Comment by Hannah-PortSwigger** [comment]
Hi Soroush

Thanks for your patience.

HttpRequest has a `toString()` method on it, so you don't need to use `ByteUtils`.

When creating an `HttpRequest` using raw bytes or a String, we assume that you have configured the raw request to be accurate to the content you wish to be sent out of Burp. HttpRequests typically are HTTP protocol agnostic (despite stating a protocol), as the HTTP protocol is determined when issuing the request.
Updating the relevant Content-Length header with your calculated value is one method you can use. You could also use the `withBody()` method to trigger the Content-Length to be updated.
```java
HttpRequest requestWithoutUpdatedContentLength = HttpRequest.httpRequest(interceptedRequest.httpService(), replacedString);
HttpRequest updatedContentLength = requestWithoutUpdatedContentLength.withBody(requestWithoutUpdatedContentLength.body());
```

We don't really have support or utilities for working with chunked encoding in Burp. All of the helper methods assume usage of Content-Length instead. At the moment, you would need to manage your own logic for this. HOwever, if you would like we can raise a feature request to add functionality around this. We would need to monitor the popularity of this request before we are able to properly prioritize it.

Generally speaking, the only time you should need to use `HttpRequest.http2Request()` is when trying to create a "kettled" request. As briefly mentioned before, the HTTP protocol is largely decided when issuing the request. If the extension is issuing the request, you can force the `HttpMode` by using `Http.sendRequest(HttpRequest request, HttpMode httpMode)`. When using `continueWith()` as part of the Proxy or Http Handlers, this should be controlled by Burp's settings (Settings > Network > HTTP > HTTP/2 > Default to HTTP/2 if the server supports it).

**Comment by irsdl** [comment]
Thank you @Hannah-PortSwigger , it really helped. I cannot recreate the connection drop issue I had when I had used `HttpRequest.httpRequest` for both HTTP2 and HTTP1. That said, I still think the `http2Request` method should be compatible with  the `httpRequest` method in terms of accepting the same input parameter types so they can be replaced easily.
The `http2Request` method also needs it simpler for users to mention the path, querystring, and the http method by one call (instead of calling `.withMethod(interceptedRequest.method()).withPath(interceptedRequest.path().replaceAll(highlightMatcherToBeRemoved.group(0),""))` afterwards.

I am also now interested to see if you have any examples of using the `http2Request` method for "kettling!" as I have no idea how this can be done without looking at other people's code.

**Comment by Hannah-PortSwigger** [comment]
I don't have any example extensions that make use of this with Montoya API, but if you think this would be useful we could look at putting together an extension for the Examples repo.

What I've referred to as kettling is providing non-standard input as part of the headers in an HTTP/2 request, used as part of request smuggling. For example, adding new lines into a header value in order to smuggle data through to the server. If this gets downgraded to HTTP/1 by a server, this can potentially get interpreted as a line by the server and processed accordingly.

You can find out more information about this in our Request Smuggling Web Security Academy topic:
- https://portswigger.net/web-security/request-smuggling/advanced#request-smuggling-via-crlf-injection
- https://portswigger.net/web-security/request-smuggling/advanced/http2-exclusive-vectors
- https://portswigger.net/web-security/request-smuggling/advanced/lab-request-smuggling-h2-request-smuggling-via-crlf-injection

This is quite a niche use case, so we would recommend avoiding the use of the `http2Request` method unless necessary. If needed, as you mentioned, you can use the `with` methods to adjust the path, query string, and method.

Overall, using on the standard request factory methods to create your requests should be reliable for most standard use cases. Requests will be upgraded or downgraded depending on the protocol Burp is sending it with.
If you're unsure whether a request has been sent with HTTP/1 or HTTP/2, opening the "Request attributes" section of the Inspector panel should quickly show you.

**Comment by irsdl** [comment]
Thank you very much for taking your time and answering my questions. I have now updated my Sharpener extension with a new highlighting feature that uses your advise: https://github.com/irsdl/BurpSuiteSharpenerEx/blob/main/src/main/java/ninja/burpsuite/extension/sharpener/capabilities/implementations/ManualHighlighterRequestResponseHandler.java#L39

**Comment by Hannah-PortSwigger** [comment]
Glad to hear that helped! If there's anything else we can help with, then please let us know.
