### ISSUE TITLE
Bug: number of highlights is not set when using Editor.setSearchExpression()

### ISSUE THREAD

**Issue by serkonda7** [PortSwigger/burp-extensions-montoya-api#86]
In my code I ran `respEditor.setSearchExpression("Server:")`.

See the screenshot below.
It should be `2 Highlights` while it is `0 Highlights`

![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/40118727/bb09d2c8-d8e5-44bb-988e-0354f8fe981b)

**Comment by Hannah-PortSwigger** [comment]
Hi. Could you tell me the version of Burp that you are using?

I've attempted to replicate this issue on our Stable and Early Adopter channel, but have not been successful.

**Comment by serkonda7** [comment]
It was version 2023.09.
I haven't tested 2023.10 yet
