### ISSUE TITLE
Feature Request: Extension Action Handler Parameters and Action Flow Control

### ISSUE THREAD

**Issue by eku952** [PortSwigger/burp-extensions-montoya-api#92]
### Background
I'm currently developing an extension to assist users in managing multiple sessions. Part of that is I want to allow for users to create session handling rules for each tracked session. Similar to the `Check session is valid` action, I want to be able to invoke a custom action to check for a unique identifier in the original request (which is supplied by the user) as well as the session handling rule context, and from there either execute a set of macros, invoke an additional rule action, or pass the request along.

### The Issues
Unfortunately, I haven't found an effective way to achieve this with the API. The two main problems I'm running into are:
1. If the extension rule action determines that the current request should be passed through, there's no way for it to skip following rule actions or inform them that they should also pass the request through. For example, if a session handling rule has a `Check session is valid` action that should only trigger when a request contains session identifier `user1`, but a request has the identifier `user2`, there's no way for the extension action to skip the `Check session is valid` action.
2. There doesn't seem to be a way to pass additional information to the extension action. Ideally, I'd like to be able to pass a parameter to the extension action from the session handling rule that tells it what session the rule is meant to be handling. This would make it much easier for the extension to determine if it needs to act on the incoming request.

### My Suggestions
- Allow for extension actions to stop consecutive actions from executing if the extension determines further processing of the request is unnecessary
- Allow for parameters to be passed to extension actions. Parameter criteria, such as expected data typed, could be set when an extension registers an action handler. Parameters could then be configured in the action editor.
- Supply the details of the session handling rule that is triggering the extension action, such as the rule description and scoping information. This can further help extension actions determine if they need to act on a request.

Please let me know if you have any questions!

**Comment by Hannah-PortSwigger** [comment]
Hi.

It is possible to retrieve details about the session handling rule as part of your extension. You can do this by retrieving the project-level configuration settings.

You can find some examples of extensions that make use of this functionality here:
- https://github.com/Hannah-PortSwigger/ClientCredentialsOauth
- https://github.com/Hannah-PortSwigger/TOTPAuthenticate

With regards to an extension preventing further consecutive actions or skipping actions, this isn't likely to be functionality we implement as this rule list is provided and configured by the user. This means that a user has explicitly set that they would like the rule action to happen.

Could you provide some more context around the functionality you would be looking for? You could perform session validation within your session handling action, or recommend a different order of rules.

**Comment by eku952** [comment]
Hello.

Thank you for letting me know about retrieving project-level configuration settings. I'll take a look at those extensions and see how I could implement that into my project.

The way my extension works is users add session cookies they want to keep track of into a table. For each cookie, the user provides a unique identifier that can be referenced from any tool within Burp. Then for each HTTP request that is sent, the extension checks for the presence of the identifier, looks up the session cookie in its table, replaces the identifier with the cookie in the request, and sends the request forward.

Here's what the session table currently looks like:
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/14254199/897657e4-9220-433f-a902-98b90a141226)

For each request, the user references the identifier by inserting `$$IDENTIFIER` into the `Cookie` header:
```
GET /users/settings HTTP/1.1
Host: localhost:4000
Cookie: _carafe_key=$$user1
```

When the request is sent, the extension replaces the identifier with the cookie stored in the table:
```
GET /users/settings HTTP/1.1
Host: localhost:4000
Cookie: _carafe_key=SFMyNTY.g3QAAAADbQAAAAtfY3NyZl90b2tlbm0AAAAYemwwTWYxR2NKT1QzUUhFVHF4S1RZN25SbQAAAA5saXZlX3NvY2tldF9pZG0AAAA7dXNlcnNfc2Vzc2lvbnM6dE5NU3pfLXBIV0ExSW13N1hqOVlWeHVFSUVySXFVdnNtYVVyc18zaFlSZz1tAAAACnVzZXJfdG9rZW5tAAAAILTTEs__qR1gNSJsO14_WFcbhCBKyKlL7JmlK7P94WEY.fIfukHeF5ywxgkH-lfZqNSMefKh1YatnsiH5JzvICQ8
```

Specifically for my test application, whenever a request is made to an authenticated endpoint with an invalid session, it redirects the user back to the login page.
```
HTTP/1.1 302 Found
location: /users/log_in
server: Cowboy
```

In order to set up session handling rules for `user1` and `user2`, I need to be able to analyze the original request to look for the session identifier and analyze the response to check for a redirect to the `/users/log_in` page. Afterwards, I would need to execute a set of macros specific to either `user1` or `user2`, retrieve the value in the `set-cookie` header, update the session table, and resend the original request with the new cookie value.

The closest thing that exists currently is the `Check session is valid` action. However, that rule only supports analyzing the original response, and I need to be able to analyze **both** the original response and request.

Is there a way to achieve this using existing functionality?

**Comment by Hannah-PortSwigger** [comment]
It sounds like you may be better off providing this functionality on an HttpHandler instead.

By doing this, you get access to both the request to perform the substitution in `handleHttpRequestToBeSent()`, and the response with `initiatingRequest()` in `handleHttpResponseReceived()`.

You could map the `initiaingRequest()` back to items in your table by the current session token that they have set.

This would mean that any macro style requests will need to be handled by your extension, but there have been other cases of extensions reimplementing this functionality. [Authentication Token Obtain and Replace](https://portswigger.net/bappstore/51327b097b354243b307b4ed87ba39eb) is an example of an extension that implements complex macro functionality within their extension.
