### ISSUE TITLE
HttpService.ipAddress() is not implemented

### ISSUE THREAD

**Issue by danzajork** [PortSwigger/burp-extensions-montoya-api#93]
HttpService.ipAddress() is not implemented when accessing HttpService through ProxyHttpRequestResponse. 

The following exception is thrown:

```
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.HttpService.ipAddress()'
```

The following code will reproduce this error:

```java
List<ProxyHttpRequestResponse> history = api.proxy().history();

for (ProxyHttpRequestResponse httpRequestResponse: history) {

     String ipAddress = httpRequestResponse.httpService().ipAddress();
}
```

The following code will also reproduce this error:

```java
List<ProxyHttpRequestResponse> history = api.proxy().history();

for (ProxyHttpRequestResponse httpRequestResponse: history) {

     String ipAddress = httpRequestResponse.finalRequest().httpService().ipAddress();
}
```

**Comment by danzajork** [comment]
My bad, this is on me.

I was using montoya 2023.12.1 while running the current stable release of Burp (2023.11.1.5). 

This is working correctly in the early adopter channel. Closing this issue.

**Comment by Hannah-PortSwigger** [comment]
Glad to hear you've resolved the issue!

If there's anything else we can help with, then please let us know.
