### ISSUE TITLE
how httpRequestResponse  transform to  proxyHttpRequestResponse

### ISSUE THREAD

**Issue by InfiniteOpen** [PortSwigger/burp-extensions-montoya-api#95]
Hi ,i use the montoya api version is:  `net.portswigger.burp.extensions:montoya-api:2023.1`. 

When i writing a plugin for burpsuite, try to add a `burp.api.montoya.http.message.HttpRequestResponse` to proxy history panle.

I hope the burp.api.montoya.proxy.ProxyHttpRequestResponse cloud add a static function to transform the `burp.api.montoya.http.message.HttpRequestResponse` like

static ProxyHttpRequestResponse proxyHttpRequestResponse (HttpRequestResponse httpRequestResponse)

**Comment by InfiniteOpen** [comment]
Thanks your answer,I use the `burp.api.montoya.http.Http#sendRequest(burp.api.montoya.http.message.requests.HttpRequest)` to send a request , but the request can't through the Proxy tool, i can just find the log in Burpsuite Logger Panel, is there any way make the request through the proxy tool ?

**Comment by Hannah-PortSwigger** [comment]
Using `sendRequest()` will initiate an outgoing request from Burp. As you've seen, this will show up in Logger as it has passed through Burp's network stack. However, it will not show in the Proxy HTTP History, as it has not been proxied through Burp.

If you want to have a request pass through the Proxy tool, you can do this in a couple of different ways:
- Make a request with a browser that has a proxy set to pass through Burp's proxy listener
- Use Burp's built-in browser to make a request
- Make a request using curl with the proxy argument set to Burp's proxy listener
- I found [this article](https://dev.to/anderrv/http-requests-in-java-with-proxies-30n8) on making requests via a proxy using Java's networking

Are you able to provide some more information on what functionality you are trying to provide with your extension? We may be able to recommend some alternatives.

**Comment by InfiniteOpen** [comment]
Thanks your answer , but thoese way not fit to me,i just want the request made by burpsuite exension that using the montoya lib, could through the Proxy too
