### ISSUE TITLE
How to modify the selected text index?

### ISSUE THREAD

**Issue by yinsel** [PortSwigger/burp-extensions-montoya-api#98]
```java
List<Component> menus = new ArrayList<>();
            JMenuItem encodeMenuItem = new JMenuItem("encode");
            JMenuItem decodeMenuItem = new JMenuItem("decode");
            encodeMenuItem.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Optional<MessageEditorHttpRequestResponse> messageEditorHttpRequestResponse = event.messageEditorRequestResponse();
                    if (messageEditorHttpRequestResponse.isPresent()) {
                        HttpRequestResponse messageInfo = messageEditorHttpRequestResponse.get().requestResponse();
                        Optional<Range> selectionBounds = messageEditorHttpRequestResponse.get().selectionOffsets();
                        if (selectionBounds.isPresent()) {
                            Range range = selectionBounds.get();
                            int start = range.startIndexInclusive();
                            int end = range.endIndexExclusive();
                            byte[] request = messageInfo.request().toByteArray().getBytes();
                            String selectedText = new String(request, start, end - start);
                            String encodedText = encodeToUnicode(selectedText);
                            byte[] newRequest = new byte[request.length - (end - start) + encodedText.length()];
                            System.arraycopy(request, 0, newRequest, 0, start);
                            System.arraycopy(encodedText.getBytes(), 0, newRequest, start, encodedText.getBytes().length);
                            System.arraycopy(request, end, newRequest, start + encodedText.length(), request.length - end);
                            HttpRequest newHttpRequest = HttpRequest.httpRequest(messageInfo.request().httpService(), ByteArray.byteArray(newRequest));
                            messageEditorHttpRequestResponse.get().setRequest(newHttpRequest);
                        }
                    }
                }
            });
```

I want to create a small plugin for right-click Unicode encoding, but I found that users do not know how long the encoded text is. In BurpSuite's native Base64 encoding, the encoded text will be automatically selected.
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/91541985/1b1a8f26-d337-46bc-a6eb-4e4b555e5d69)
![image](https://github.com/PortSwigger/burp-extensions-montoya-api/assets/91541985/a6a2c5c6-799c-4baa-a6e0-5021f8eccf7d)
I want to modify the index of Range, but it is not provided in the API. Range provides a static method to create a Range object, and MessageEditorHttpRequestResponse does not have a setRange method. I would like to seek help here.

**Comment by Hannah-PortSwigger** [comment]
Hi

Could you provide some more information about what you are trying to achieve?

Are you looking to modify the HttpRequestResponse and change the selected data by encoding or decoding it?

**Comment by yinsel** [comment]
> Hi
> 
> Could you provide some more information about what you are trying to achieve?
> 
> Are you looking to modify the HttpRequestResponse and change the selected data by encoding or decoding it?
> 
> 
> 嗨
> 
> 你能提供更多关于你正在努力实现的目标的信息吗？
> 
> 您是否希望修改HttpRequestResponse并通过编码或解码更改所选数据？

Yes, and the modified data will be automatically selected again

**Comment by Hannah-PortSwigger** [comment]
Hi

You should be able to adjust the contents of the editor to update with your new content. However, it will not be possible to adjust the user's currently selected data as this is manually controlled by the user.

**Comment by yinsel** [comment]
> 你好
> 
> 您应该能够调整编辑器的内容以使用新内容进行更新。但是，由于这是由用户手动控制的，因此无法调整用户当前选择的数据。

Can you provide sample code to modify the editor's selection?

**Comment by yinsel** [comment]
> 你好
> 
> 您应该能够调整编辑器的内容以使用新内容进行更新。但是，由于这是由用户手动控制的，因此无法调整用户当前选择的数据。



> 你好
> 
> 您应该能够调整编辑器的内容以使用新内容进行更新。但是，由于这是由用户手动控制的，因此无法调整用户当前选择的数据。

In addition, burpsuite's built-in right-click base64 encoding function enables re-selection of content, and I thought that extensions could also be achieved

**Comment by Hannah-PortSwigger** [comment]
There's an example of an extension that inserts data into a Repeater panel here: https://github.com/Hannah-PortSwigger/InsertHexString/blob/main/src/main/java/Extension.java

This does not replace content based on a selection, but works in a similar way to build the new request and set it within the editor.

When trying to make modifications to data, it must be within an editable text editor rather than a read-only editor.

**Comment by yinsel** [comment]
> There's an example of an extension that inserts data into a Repeater panel here: https://github.com/Hannah-PortSwigger/InsertHexString/blob/main/src/main/java/Extension.java
> 
> This does not replace content based on a selection, but works in a similar way to build the new request and set it within the editor.
> 
> When trying to make modifications to data, it must be within an editable text editor rather than a read-only editor.

Thank you!
